package com.shminjs.leetcode.easy;

/**
 * Created by shimin on 2017/6/6.
 * 389
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one or more letter at a random position.
 * Find the letter that was add in t.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] s_arr = new int[26];
        int[] t_arr = new int[26];
        for (int i = 0; i < s.length(); i++) {
            s_arr[s.charAt(i)-97]++;
        }
        for (int i = 0; i < t.length(); i++) {
            t_arr[t.charAt(i)-97]++;
        }
        for (int i = 0; i < 26; i++) {
            if (s_arr[i] != t_arr[i]) {
                return (char)(i+97);
            }
        }
        return '\0';
    }
}
